In [1]:
import pandas as pd
import numpy as np
import string
import tensorflow as tf
import keras
from keras import layers
import re
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import Perceptron

In [112]:
# Augmented data for LLM - Detect AI Generated Text by jdragonxherrera on Kaggle
df = pd.read_csv('../Data/training.csv')

In [3]:
max_features = 20000
embedding_dim = 64
sequence_length = 500

In [95]:
shuffled_df = df.sample(frac=1, random_state=1818)
# Remove 80% of the data
num_samples_to_remove = int(0.8 * len(shuffled_df))
remaining_df = shuffled_df.iloc[num_samples_to_remove:]


train_df, remaining_df = train_test_split(remaining_df, train_size=0.8, random_state=1818)
val_df, test_df = train_test_split(remaining_df, train_size=0.5, random_state=1818)

def custom_standardization(input_data):
    lowercase = tf.strings.lower(input_data)
    stripped_html = tf.strings.regex_replace(lowercase, "<br />", " ")
    return tf.strings.regex_replace(
        stripped_html, f"[{re.escape(string.punctuation)}]", ""
    )

vectorize_layer = keras.layers.TextVectorization(
    standardize=custom_standardization,
    max_tokens=max_features,
    output_mode="int",
    output_sequence_length=sequence_length,
)

ds = tf.data.Dataset.from_tensor_slices((df['text'].values))
ds = ds.batch(512)
vectorize_layer.adapt(ds)

# Vectorize the data

train_text = np.array(vectorize_layer(train_df['text']))
val_text = np.array(vectorize_layer(val_df['text']))
test_text = np.array(vectorize_layer(test_df['text']))

train_labels = np.array(train_df['label'])
val_labels = np.array(val_df['label'])
test_labels = np.array(test_df['label'])

In [57]:
# A integer input for vocab indices.
inputs = keras.Input(shape=(None,), dtype="int64")

x = layers.Embedding(max_features, embedding_dim)(inputs)
x = layers.Dropout(0.5)(x)

# Conv1D + global max pooling
x = layers.Conv1D(64, 7, padding="valid", activation="relu", strides=3)(x)
x = layers.Conv1D(64, 7, padding="valid", activation="relu", strides=3)(x)
x = layers.GlobalMaxPooling1D()(x)

# Add a vanilla hidden layer:
x = layers.Dense(64, activation="relu")(x)
x = layers.Dropout(0.5)(x)

# Output layer
predictions = layers.Dense(1, activation="sigmoid", name="predictions")(x)

model = keras.Model(inputs, predictions)

# Compile the model with binary crossentropy loss and an adam optimizer.
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

epochs = 3

# Fit the model using the train and val datasets.
model.fit(train_text, train_labels, validation_data=(val_text, val_labels), epochs=epochs)

Epoch 1/3
2168/2168 [==============================] - 24s 11ms/step - loss: 0.0919 - accuracy: 0.9626 - val_loss: 0.0238 - val_accuracy: 0.9930
Epoch 2/3
2168/2168 [==============================] - 23s 11ms/step - loss: 0.0204 - accuracy: 0.9937 - val_loss: 0.0191 - val_accuracy: 0.9946
Epoch 3/3
2168/2168 [==============================] - 23s 11ms/step - loss: 0.0124 - accuracy: 0.9961 - val_loss: 0.0175 - val_accuracy: 0.9942


In [34]:
combined_data = pd.read_csv('../Data/Detect AI Generated Text/combined_essays.csv')
# Drop the id, prompt_id, text_len, and model columns
combined_data = combined_data.drop(['id', 'prompt_id', 'text_len', 'model'], axis=1)
# Rename the 'generated' column to 'label'
combined_data = combined_data.rename(columns={'generated': 'label'})
# Convert the label column to a boolean and the text column to a string
combined_data['label'] = combined_data['label'].astype(bool)
combined_data['text'] = combined_data['text'].astype(str)

cd_text = np.array(vectorize_layer(combined_data['text']))
cd_labels = np.array(combined_data['label'])

In [62]:
print("Evaluate on test data")
results = model.evaluate(test_text, test_labels)
print("test loss, test acc:", results)
results = model.evaluate(cd_text, cd_labels, batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
271/271 [==============================] - 0s 1ms/step - loss: 0.0230 - accuracy: 0.9932
test loss, test acc: [0.0230079498142004, 0.9931964874267578]
22/22 [==============================] - 0s 4ms/step - loss: 0.0900 - accuracy: 0.9775
test loss, test acc: [0.09002448618412018, 0.9775036573410034]


In [ ]:
'''
Model 2 accuracy was 0.9905/0.9811 & 0.9905/0.9601
Model 3 epoch 3 accuracy was 0.9818/0.9677 & 0.9818/0.9968
Model 3 epoch 6 accuracy was 0.9908/0.9586 
Model 3 epoch 3 0.6 accuracy was 0.9905/0.9811 
'''

In [92]:
vectorizer = TfidfVectorizer(max_features=max_features)
vectorizer.fit(df['text'])


In [96]:
train_vectors = vectorizer.transform(train_df['text'])
test_vectors = vectorizer.transform(test_df['text'])

In [93]:

cd_vectors = vectorizer.transform(combined_data['text'])
cd_labels = combined_data['label'].to_numpy()

In [97]:
perceptron_model = Perceptron(max_iter=1000)
perceptron_model.fit(train_vectors, train_labels)

# Make predictions on the test set
predictions = perceptron_model.predict(test_vectors)

# Evaluate the accuracy
accuracy = accuracy_score(test_labels, predictions)
print(f"Accuracy: {accuracy:.2f}")

# classification report
print(classification_report(test_labels, predictions))

# confusion matrix
print(confusion_matrix(test_labels, predictions))

Accuracy: 0.99
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      5508
           1       0.99      0.99      0.99      3164

    accuracy                           0.99      8672
   macro avg       0.99      0.99      0.99      8672
weighted avg       0.99      0.99      0.99      8672

[[5486   22]
 [  45 3119]]


In [110]:
class Classifier():
    def __init__(self, tensor_model, perceptron_model):
        self.tensor_model = tensor_model
        self.perceptron_model = perceptron_model

    def fit(self, X, y):
        # No training needed for TensorFlow model in this case
        pass

    def predict(self, X):
        # Convert the dataset to the expected format
        tensor_X = np.array(vectorize_layer(X))
        tensor_predictions = self.tensor_model.predict(tensor_X)
        tensor_predictions = np.array(tensor_predictions).flatten()
        perceptron_X = vectorizer.transform(X)
        perceptron_predictions = self.perceptron_model.predict(perceptron_X)
        # Turn the perceptron predictions into a 1D array of floats
        perceptron_predictions = np.array(perceptron_predictions).flatten().astype(float)
        # Average the predictions along the array axis
        predictions = np.mean([tensor_predictions, perceptron_predictions], axis=0)
        # Convert the predictions to binary
        predictions = np.where(predictions > 0.5, 1, 0)
        return predictions
    
classifier = Classifier(tensor_model=model, perceptron_model=perceptron_model)
train_df, test_df = train_test_split(shuffled_df, train_size=0.8, random_state=42)

train_labels2 = train_df['label'].to_numpy()
test_labels2 = test_df['label'].to_numpy()
# Get predictions from each model
predictions = classifier.predict(test_df['text'])  # Adjust according to your TensorFlow model

print(predictions[:5], test_labels2[:5])

# Evaluate the accuracy
accuracy = accuracy_score(test_labels2, predictions)
print(f"Accuracy: {accuracy:.2f}")

# Evaluate the accuracy
accuracy = accuracy_score(test_labels2, predictions)
print(f"Binary Accuracy: {accuracy:.2f}")

# classification report
print(classification_report(test_labels2, predictions))

# confusion matrix
print(confusion_matrix(test_labels2, predictions))

2710/2710 [==============================] - 4s 2ms/step
[1 1 1 0 0] [1 1 1 0 0]
Accuracy: 0.99
Binary Accuracy: 0.99
              precision    recall  f1-score   support

           0       0.99      1.00      1.00     55334
           1       0.99      0.99      0.99     31379

    accuracy                           0.99     86713
   macro avg       0.99      0.99      0.99     86713
weighted avg       0.99      0.99      0.99     86713

[[55144   190]
 [  349 31030]]
